In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [64]:
!pip install scikit-learn
from sklearn.impute import SimpleImputer

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)

In [46]:
%matplotlib inline

In [47]:
data = pd.read_csv('/content/telcom_data.csv')

**Dataset organization**

In [48]:
data

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311450e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082010e+14,3.366496e+10,3.552120e+13,9.16457E+15,...,15854611.0,2501332.00,8198936.00,9656251.00,278082303.0,1.434415e+07,171744450.0,8.814393e+06,36749741.0,308879636.0
1,1.311450e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082020e+14,3.368185e+10,3.579400e+13,L77566A,...,20247395.0,19111729.00,18338413.00,17227132.00,608750074.0,1.170709e+06,526904238.0,1.505514e+07,53800391.0,653384965.0
2,1.311450e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082000e+14,3.376063e+10,3.528150e+13,D42335A,...,19725661.0,14699576.00,17587794.00,6163408.00,229584621.0,3.956300e+05,410692588.0,4.215763e+06,27883638.0,279807335.0
3,1.311450e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082010e+14,3.375034e+10,3.535660e+13,T21824A,...,21388122.0,15146643.00,13994646.00,1097942.00,799538153.0,1.084972e+07,749039933.0,1.279728e+07,43324218.0,846028530.0
4,1.311450e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082010e+14,3.369980e+10,3.540700e+13,D88865A,...,15259380.0,18962873.00,17124581.00,415218.00,527707248.0,3.529801e+06,550709500.0,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277830e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082020e+14,3.365069e+10,3.548310e+13,D20434A,...,16191667.0,11763428.00,17883703.00,19678161.00,526609673.0,9.197207e+06,3264510.0,1.348742e+07,57628851.0,574175259.0
149997,7.349880e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082020e+14,3.366345e+10,3.566050e+13,D10223C,...,13877234.0,8288284.00,19350146.00,21293148.00,626893062.0,4.735033e+06,712180387.0,2.457758e+06,39135081.0,666648844.0
149998,1.311450e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082020e+14,3.362189e+10,3.572120e+13,T51102A,...,22660510.0,1855903.00,9963942.00,5065760.00,553539484.0,1.339432e+07,121100856.0,1.131473e+07,34912224.0,592786405.0
149999,1.311450e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082020e+14,3.361962e+10,8.618620e+13,L88342B,...,8817106.0,8305402.00,3322253.00,13172589.00,352536971.0,2.529475e+06,814713113.0,1.406930e+06,29626096.0,371895920.0
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11634072.5,11009410.13,11626851.72,11001754.82,422044702.6,8.288398e+06,421100544.2,8.264799e+06,NaN,NaN

In [49]:
data.shape[0]

150001

In [50]:
data.shape[1]

55

In [51]:
data.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311450e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082010e+14,3.366496e+10,3.552120e+13,9.16457E+15,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311450e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082020e+14,3.368185e+10,3.579400e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311450e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082000e+14,3.376063e+10,3.528150e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311450e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082010e+14,3.375034e+10,3.535660e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311450e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082010e+14,3.369980e+10,3.540700e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [52]:
data.columns

Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 37500B < Vol UL',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with 6250B < Vol UL < 37500B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social Media DL (Bytes)', 'Social Media UL (Bytes)',
       'Google DL (Bytes)', 'Google UL (Bytes)', 'Email DL (Bytes)',
       'Email UL (Bytes)', 'Youtube DL (Bytes)', 'Youtube UL (Bytes)',
       'Netflix DL (Bytes)', 'Netflix UL (Bytes)', 'Gaming DL (Bytes)',
       'Gaming UL (Bytes)', 'Other DL (Bytes)', 'Other UL (Bytes)',
       'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [54]:
data.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.490100e+05,150000.000000,150000.000000,1.500000e+05,1.494310e+05,1.489350e+05,1.494290e+05,122172.000000,122189.000000,150000.000000,...,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500000e+05,1.500000e+05
mean,1.013887e+19,499.188200,498.800880,1.046086e+05,2.082017e+14,4.188282e+10,4.847454e+13,109.795706,17.662883,13300.045927,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,2.893170e+18,288.611834,288.097653,8.103762e+04,2.149289e+10,2.447443e+12,2.241637e+13,619.782739,84.793524,23971.878541,...,6.710569e+06,6.345423e+06,6.725218e+06,6.359490e+06,2.439675e+08,4.782700e+06,2.432050e+08,4.769004e+06,1.127639e+07,2.441429e+08
min,6.917540e+18,0.000000,0.000000,7.142000e+03,2.040470e+14,3.360100e+10,4.400150e+11,0.000000,0.000000,0.000000,...,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349880e+18,250.000000,251.000000,5.744050e+04,2.082010e+14,3.365130e+10,3.546070e+13,32.000000,2.000000,43.000000,...,5.833501e+06,5.517965e+06,5.777156e+06,5.475981e+06,2.104733e+08,4.128476e+06,2.101869e+08,4.145943e+06,3.322201e+07,2.431068e+08
50%,7.349880e+18,499.000000,500.000000,8.639900e+04,2.082020e+14,3.366371e+10,3.572200e+13,45.000000,5.000000,63.000000,...,1.161602e+07,1.101345e+07,1.164222e+07,1.099638e+07,4.234081e+08,8.291208e+06,4.218030e+08,8.267071e+06,4.114331e+07,4.558411e+08
75%,1.304240e+19,749.000000,750.000000,1.324302e+05,2.082020e+14,3.368349e+10,8.611970e+13,70.000000,15.000000,19710.750000,...,1.744852e+07,1.651556e+07,1.747048e+07,1.650727e+07,6.331742e+08,1.243162e+07,6.316918e+08,1.238415e+07,4.903424e+07,6.657055e+08
max,1.318650e+19,999.000000,999.000000,1.859336e+06,2.140740e+14,8.823970e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,...,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

In [55]:
data.columns

Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 37500B < Vol UL',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with 6250B < Vol UL < 37500B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social Media DL (Bytes)', 'Social Media UL (Bytes)',
       'Google DL (Bytes)', 'Google UL (Bytes)', 'Email DL (Bytes)',
       'Email UL (Bytes)', 'Youtube DL (Bytes)', 'Youtube UL (Bytes)',
       'Netflix DL (Bytes)', 'Netflix UL (Bytes)', 'Gaming DL (Bytes)',
       'Gaming UL (Bytes)', 'Other DL (Bytes)', 'Other UL (Bytes)',
       'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')

In [56]:
data.isnull().sum()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [57]:
data.duplicated().sum()

0

In [58]:
for col in data.columns:
    print(data[col].value_counts())

Bearer Id
7.349880e+18    39915
1.304240e+19    37251
1.311450e+19    35114
7.277830e+18    29667
6.917540e+18     5886
1.268210e+19     1003
7.421940e+18       97
1.318650e+19       76
7.566060e+18        1
Name: count, dtype: int64
Start
4/26/2019 7:25     203
4/26/2019 7:26     190
4/26/2019 7:36     175
4/26/2019 7:30     160
4/26/2019 7:46     143
                  ...
4/21/2019 8:04       1
4/21/2019 1:57       1
4/21/2019 1:56       1
4/20/2019 23:56      1
4/4/2019 12:01       1
Name: count, Length: 9997, dtype: int64
Start ms
341.0    190
624.0    183
109.0    182
248.0    180
379.0    180
        ...
582.0    121
431.0    121
665.0    117
446.0    117
917.0    117
Name: count, Length: 1000, dtype: int64
End
4/25/2019 0:01     1150
4/25/2019 0:02      418
4/25/2019 0:00      296
4/25/2019 0:48      286
4/28/2019 0:00      275
                   ...
4/28/2019 11:32       1
4/28/2019 13:54       1
4/28/2019 11:58       1
4/28/2019 10:26       1
4/30/2019 22:32       1
Name: count, Length: 6403, dtype: int64
End ms
872.0    213
576.0    205
565.0    199
444.0    196
760.0    196
        ...
712.0    112
421.0    112
226.0    112
591.0    106
336.0    106
Name: count, Length: 1000, dtype: int64
Dur. (ms)
86399.0     21413
86400.0      6437
85499.0       188
86398.0       145
86397.0       110
            ...
171697.0        1
180450.0        1
176343.0        1
180189.0        1
98249.0         1
Name: count, Length: 89525, dtype: int64
IMSI
2.082020e+14    84033
2.082010e+14    52348
2.082000e+14     9572
2.082100e+14     3474
2.140740e+14        1
2.082520e+14        1
2.040810e+14        1
2.040470e+14        1
Name: count, dtype: int64
MSISDN/Number
3.362632e+10    18
3.361489e+10    17
3.362578e+10    17
3.365973e+10    16
3.376054e+10    15
                ..
3.368998e+10     1
3.376372e+10     1
3.360748e+10     1
3.369955e+10     1
3.361962e+10     1
Name: count, Length: 106856, dtype: int64
IMEI
8.637690e+13    19752
3.540530e+13     2174
8.654080e+13     2077
3.579880e+13     1021
3.589520e+13      981
                ...
3.598040e+13        1
3.537710e+13        1
3.517510e+13        1
3.544730e+13        1
3.532800e+13        1
Name: count, Length: 3852, dtype: int64
Last Location Name
9.16457E+15    1881
8.12222E+16     187
D41377B          80
1.5328E+17       61
D17085A          59
               ...
L30051B           1
T42260C           1
D88489B           1
T85728A           1
L88342B           1
Name: count, Length: 45036, dtype: int64
Avg RTT DL (ms)
28.0      3553
27.0      3380
34.0      3296
35.0      2892
37.0      2718
          ...
5166.0       1
1450.0       1
6022.0       1
2914.0       1
4274.0       1
Name: count, Length: 2130, dtype: int64
Avg RTT UL (ms)
5.0       14663
2.0       14277
1.0       12826
4.0       10242
3.0        7935
          ...
302.0         1
709.0         1
1115.0        1
351.0         1
1503.0        1
Name: count, Length: 722, dtype: int64
Avg Bearer TP DL (kbps)
23.0        7324
43.0        4352
44.0        4186
6.0         3983
22.0        2867
            ...
30633.0        1
8387.0         1
61644.0        1
116257.0       1
63420.0        1
Name: count, Length: 41753, dtype: int64
Avg Bearer TP UL (kbps)
40.0       7794
54.0       6344
47.0       5840
53.0       4835
9.0        3812
           ...
16451.0       1
3523.0        1
21872.0       1
6709.0        1
36754.0       1
Name: count, Length: 14528, dtype: int64
TCP DL Retrans. Vol (Bytes)
1330.0        433
2660.0        219
38.0          200
92.0          192
1318.0        156
             ...
12686.0         1
18256688.0      1
3550956.0       1
18957898.0      1
16552848.0      1
Name: count, Length: 54399, dtype: int64
TCP UL Retrans. Vol (Bytes)
1330.0      1910
2660.0       937
1294.0       651
3990.0       548
1318.0       545
            ...
303295.0       1
621.0          1
317858.0       1
11287.0        1
162614.0       1
Name: count, Length: 35120, dtype: int64
DL TP < 50 Kbps (%)
100.0    87044
99.0      5512
98.0      3744
97.0      2931
96.0      2518
         ...
6.0          2
3.0          2
4.0          1
7.0          1
5.0          1
Name: count, Length: 100, dtype: int64
50 Kbps < DL TP < 250 Kbps (%)
0.0     95236
1.0      5745
2.0      5108
3.0      4685
4.0      4433
        ...
90.0        1
69.0        1
71.0        1
75.0        1
77.0        1
Name: count, Length: 84, dtype: int64
250 Kbps < DL TP < 1 Mbps (%)
0.0      104694
1.0        8313
2.0        6489
3.0        5425
4.0        4383
          ...
62.0          1
70.0          1
100.0         1
56.0          1
50.0          1
Name: count, Length: 73, dtype: int64
DL TP > 1 Mbps (%)
0.0     112181
1.0       8490
2.0       5730
3.0       4034
4.0       3101
         ...
84.0         1
79.0         1
85.0         1
70.0         1
81.0         1
Name: count, Length: 85, dtype: int64
UL TP < 10 Kbps (%)
100.0    91663
99.0     22516
98.0     12907
97.0      7233
96.0      4201
         ...
6.0          1
1.0          1
14.0         1
7.0          1
9.0          1
Name: count, Length: 98, dtype: int64
10 Kbps < UL TP < 50 Kbps (%)
0.0     117210
1.0      13502
2.0       7070
3.0       3748
4.0       2093
         ...
68.0         1
87.0         1
78.0         1
75.0         1
85.0         1
Name: count, Length: 85, dtype: int64
50 Kbps < UL TP < 300 Kbps (%)
0.0     144666
1.0       2013
2.0        710
3.0        400
4.0        216
         ...
43.0         1
58.0         1
38.0         1
68.0         1
56.0         1
Name: count, Length: 68, dtype: int64
UL TP > 300 Kbps (%)
0.0     146752
1.0       1075
2.0        393
3.0        240
4.0        149
         ...
32.0         1
69.0         1
88.0         1
50.0         1
40.0         1
Name: count, Length: 63, dtype: int64
HTTP DL (Bytes)
3.629000e+03    266
8.749000e+03    238
4.140000e+02    175
9.200000e+01    157
1.720000e+02    127
               ...
6.028600e+04      1
7.361000e+04      1
3.207841e+08      1
2.967112e+09      1
1.638899e+07      1
Name: count, Length: 63527, dtype: int64
HTTP UL (Bytes)
981.0        416
3282.0       304
547.0        164
2357.0       118
612.0         86
            ...
577244.0       1
911006.0       1
1196250.0      1
8731603.0      1
2672663.0      1
Name: count, Length: 59942, dtype: int64
Activity Duration DL (ms)
0.0          7278
1.0            21
508.0          13
654.0          13
2.0            13
             ...
3734531.0       1
1574215.0       1
678505.0        1
1663616.0       1
13405.0         1
Name: count, Length: 102560, dtype: int64
Activity Duration UL (ms)
0.0          5186
1.0            31
8.0            26
2.0            22
5.0            20
             ...
730981.0        1
4177996.0       1
1191943.0       1
541948.0        1
34088.0         1
Name: count, Length: 106292, dtype: int64
Dur. (ms).1
86399953.0     215
86399957.0     215
86399966.0     210
86399972.0     207
86399941.0     206
              ...
683646062.0      1
715221470.0      1
690782390.0      1
696126117.0      1
97910631.0       1
Name: count, Length: 122871, dtype: int64
Handset Manufacturer
Apple                               59565
Samsung                             40839
Huawei                              34423
undefined                            8987
Sony Mobile Communications Ab         980
                                    ...
Pt. Arga Mas Lestari                    1
Doke Communication (Hk) Limited         1
Vastking Technology (Hk) Limited        1
Mobiwire Sas                            1
Shenzhen Gaoxinqi                       1
Name: count, Length: 170, dtype: int64
Handset Type
Huawei B528S-23A                                           19752
Apple iPhone 6S (A1688)                                     9419
Apple iPhone 6 (A1586)                                      9023
undefined                                                   8987
Apple iPhone 7 (A1778)                                      6326
                                                           ...
Tct Mobile Suzho. Alcatel One Touch Y580D                      1
Shenzhen Fortune. M-Ppas6                                      1
Wiko Global Sasu Wiko Ridge 4G                                 1
Hongkong Ipro Te. Ipro I9350 I9400 S3 Wave 3.5 Wave 4.0        1
Shenzhen Jeko Co. Blackview Bv5800 Pro                         1
Name: count, Length: 1396, dtype: int64
Nb of sec with 125000B < Vol DL
1.0        1977
2.0        1562
3.0        1181
4.0        1043
5.0         840
           ...
28030.0       1
4159.0        1
2128.0        1
4204.0        1
7770.0        1
Name: count, Length: 6458, dtype: int64
Nb of sec with 1250B < Vol UL < 6250B
1.0        3566
2.0        2396
3.0        1744
4.0        1449
5.0        1217
           ...
48126.0       1
2389.0        1
3748.0        1
3138.0        1
1833.0        1
Name: count, Length: 3398, dtype: int64
Nb of sec with 31250B < Vol DL < 125000B
1.0        2549
2.0        1491
3.0        1055
4.0         865
5.0         735
           ...
7856.0        1
6207.0        1
3076.0        1
10163.0       1
5997.0        1
Name: count, Length: 5755, dtype: int64
Nb of sec with 37500B < Vol UL
1.0       3442
2.0       1901
3.0       1262
4.0        933
5.0        738
          ...
958.0        1
1320.0       1
653.0        1
2036.0       1
1776.0       1
Name: count, Length: 1104, dtype: int64
Nb of sec with 6250B < Vol DL < 31250B
1.0        2434
2.0        1560
3.0        1112
4.0         844
5.0         746
           ...
12881.0       1
8895.0        1
15856.0       1
4668.0        1
17800.0       1
Name: count, Length: 6172, dtype: int64
Nb of sec with 6250B < Vol UL < 37500B
1.0       5781
2.0       3674
3.0       2590
4.0       1948
5.0       1609
          ...
1414.0       1
7072.0       1
611.0        1
6228.0       1
2031.0       1
Name: count, Length: 1710, dtype: int64
Nb of sec with Vol DL < 6250B
3.0        951
2.0        804
4.0        800
5.0        619
6.0        570
          ...
31631.0      1
67205.0      1
24578.0      1
19301.0      1
17006.0      1
Name: count, Length: 22270, dtype: int64
Nb of sec with Vol UL < 1250B
1.0        637
3.0        584
4.0        563
93.0       530
91.0       522
          ...
14714.0      1
13591.0      1
24268.0      1
14219.0      1
43438.0      1
Name: count, Length: 22976, dtype: int64
Social Media DL (Bytes)
2106903.000    3
2506271.000    3
1132416.000    3
924391.000     3
1700385.000    3
              ..
2040408.000    1
952572.000     1
1353792.000    1
2097660.000    1
1795321.774    1
Name: count, Length: 146856, dtype: int64
Social Media UL (Bytes)
55156.00000    11
30810.00000    11
56229.00000    11
42902.00000    11
36509.00000    10
               ..
19871.00000     1
20688.00000     1
31518.00000     1
18570.00000     1
32928.43438     1
Name: count, Length: 59078, dtype: int64
Google DL (Bytes)
7.696054e+06    3
6.296014e+06    3
3.991481e+06    3
9.003594e+06    3
6.839538e+06    3
               ..
4.191547e+06    1
5.071110e+06    1
1.124745e+07    1
9.814330e+06    1
5.750753e+06    1
Name: count, Length: 149024, dtype: int64
Google UL (Bytes)
3426526.000    4
644778.000     3
3120980.000    3
3658664.000    3
1997007.000    3
              ..
1324344.000    1
2266.000       1
2201959.000    1
143985.000     1
2056541.926    1
Name: count, Length: 147267, dtype: int64
Email DL (Bytes)
1829513.000    4
136430.000     3
1113690.000    3
1120616.000    3
271669.000     3
              ..
2977247.000    1
2120123.000    1
2499799.000    1
1378646.000    1
1791728.868    1
Name: count, Length: 146916, dtype: int64
Email UL (Bytes)
370236.0000    4
53137.0000     4
197335.0000    4
505716.0000    4
637913.0000    4
              ..
90499.0000     1
88652.0000     1
696132.0000    1
334492.0000    1
467373.4419    1
Name: count, Length: 138699, dtype: int64
Youtube DL (Bytes)
18869169.0    3
2792362.0     2
18028862.0    2
23213056.0    2
263589.0      2
             ..
17985957.0    1
1322995.0     1
15965082.0    1
22126744.0    1
11634072.5    1
Name: count, Length: 149547, dtype: int64
Youtube UL (Bytes)
3398443.00     3
18258493.00    2
4865222.00     2
4237348.00     2
12532419.00    2
              ..
9049888.00     1
1921798.00     1
10619263.00    1
10948486.00    1
11009410.13    1
Name: count, Length: 149477, dtype: int64
Netflix DL (Bytes)
2097111.00     3
39121.00       2
17593717.00    2
18790565.00    2
3684975.00     2
              ..
18948568.00    1
22814106.00    1
18202600.00    1
17363848.00    1
11626851.72    1
Name: count, Length: 149518, dtype: int64
Netflix UL (Bytes)
1751610.00     3
15570353.00    2
14199212.00    2
20560763.00    2
10578345.00    2
              ..
5539633.00     1
8446102.00     1
12613851.00    1
16484327.00    1
11001754.82    1
Name: count, Length: 149490, dtype: int64
Gaming DL (Bytes)
686236137.0    2
768107296.0    2
798867494.0    2
647606943.0    2
388832426.0    2
              ..
316783349.0    1
482968896.0    1
55807308.0     1
539002898.0    1
422044702.6    1
Name: count, Length: 149983, dtype: int64
Gaming UL (Bytes)
1.530467e+07    3
2.310099e+06    2
8.928646e+06    2
2.253719e+06    2
8.971079e+06    2
               ..
1.777644e+06    1
1.571832e+07    1
1.419785e+07    1
9.811118e+06    1
8.288398e+06    1
Name: count, Length: 149316, dtype: int64
Other DL (Bytes)
249961323.0    2
141465209.0    2
600764022.0    2
160563292.0    2
626199661.0    2
              ..
180242761.0    1
709714178.0    1
29863451.0     1
518035864.0    1
421100544.2    1
Name: count, Length: 149986, dtype: int64
Other UL (Bytes)
8.521566e+06    3
8.125986e+06    3
4.514572e+06    3
9.701036e+06    3
1.636457e+07    2
               ..
6.502786e+06    1
1.218924e+07    1
5.822650e+05    1
5.712382e+06    1
8.264799e+06    1
Name: count, Length: 149284, dtype: int64
Total UL (Bytes)
39580239.0    2
33541506.0    2
53474748.0    2
35918653.0    2
50667727.0    2
             ..
33923516.0    1
38899032.0    1
48845281.0    1
22078677.0    1
29626096.0    1
Name: count, Length: 149728, dtype: int64
Total DL (Bytes)
595801454.0    2
490686409.0    2
636139550.0    2
786752997.0    2
873317432.0    2
              ..
608841270.0    1
333160826.0    1
596330542.0    1
180066602.0    1
371895920.0    1
Name: count, Length: 149987, dtype: int64

**Replace value with zero**

In [59]:
def drop_high_missing_columns(data, threshold):
    missing_proportions = data.isnull().sum() / len(data)
    columns_to_drop = missing_proportions[missing_proportions >= threshold].index
    return data.drop(columns_to_drop, axis=1)

In [60]:
df = drop_high_missing_columns(data, 0.7)
df.columns

Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social Media DL (Bytes)', 'Social Media UL (Bytes)',
       'Google DL (Bytes)', 'Google UL (Bytes)', 'Email DL (Bytes)',
       'Email UL (Bytes)', 'Youtube DL (Bytes)', 'Youtube UL (Bytes)',
       'Netflix DL (Bytes)', 'Netflix UL (Bytes)', 'Gaming DL (Bytes)',
       'Gaming UL (Bytes)', 'Other DL (Bytes)', 'Other UL (Bytes)',
       'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')

In [61]:
def remove_missing_values():
    columns_to_check = [
    'Start',
    'Start ms',
    'End',
    'End ms',
    'Dur. (ms)',
    'Avg Bearer TP DL (kbps)',
    'Avg Bearer TP UL (kbps)',
    'Activity Duration DL (ms)',
    'Activity Duration UL (ms)',
    'Dur. (ms).1',
    'Total UL (Bytes)',
    'Total DL (Bytes)'
    ]

    return df.dropna(subset=columns_to_check)

cleaned_df = remove_missing_values()

In [62]:
df.shape

(150001, 53)

In [63]:
cleaned_df.isnull().sum()

Bearer Id                                     990
Start                                           0
Start ms                                        0
End                                             0
End ms                                          0
Dur. (ms)                                       0
IMSI                                          569
MSISDN/Number                                1065
IMEI                                          571
Last Location Name                           1152
Avg RTT DL (ms)                             27828
Avg RTT UL (ms)                             27811
Avg Bearer TP DL (kbps)                         0
Avg Bearer TP UL (kbps)                         0
TCP DL Retrans. Vol (Bytes)                 88145
TCP UL Retrans. Vol (Bytes)                 96648
DL TP < 50 Kbps (%)                           753
50 Kbps < DL TP < 250 Kbps (%)                753
250 Kbps < DL TP < 1 Mbps (%)                 753
DL TP > 1 Mbps (%)                            753
UL TP < 10 Kbps (%)                           791
10 Kbps < UL TP < 50 Kbps (%)                 791
50 Kbps < UL TP < 300 Kbps (%)                791
UL TP > 300 Kbps (%)                          791
HTTP DL (Bytes)                             81473
HTTP UL (Bytes)                             81809
Activity Duration DL (ms)                       0
Activity Duration UL (ms)                       0
Dur. (ms).1                                     0
Handset Manufacturer                          571
Handset Type                                  571
Nb of sec with 125000B < Vol DL             97537
Nb of sec with 1250B < Vol UL < 6250B       92893
Nb of sec with 31250B < Vol DL < 125000B    93585
Nb of sec with 6250B < Vol DL < 31250B      88316
Nb of sec with Vol DL < 6250B                 754
Nb of sec with Vol UL < 1250B                 792
Social Media DL (Bytes)                         0
Social Media UL (Bytes)                         0
Google DL (Bytes)                               0
Google UL (Bytes)                               0
Email DL (Bytes)                                0
Email UL (Bytes)                                0
Youtube DL (Bytes)                              0
Youtube UL (Bytes)                              0
Netflix DL (Bytes)                              0
Netflix UL (Bytes)                              0
Gaming DL (Bytes)                               0
Gaming UL (Bytes)                               0
Other DL (Bytes)                                0
Other UL (Bytes)                                0
Total UL (Bytes)                                0
Total DL (Bytes)                                0
dtype: int64

**Impute columns with the mean value**

In [66]:
def impute_columns():
    columns_to_impute = [
        "Avg RTT DL (ms)",
        "Avg RTT UL (ms)",
        "TCP DL Retrans. Vol (Bytes)",
        "TCP UL Retrans. Vol (Bytes)",
        "DL TP < 50 Kbps (%)",
        "50 Kbps < DL TP < 250 Kbps (%)",
        "250 Kbps < DL TP < 1 Mbps (%)",
        "DL TP > 1 Mbps (%)",
        "UL TP < 10 Kbps (%)",
        "10 Kbps < UL TP < 50 Kbps (%)",
        "50 Kbps < UL TP < 300 Kbps (%)",
        "UL TP > 300 Kbps (%)",
        "HTTP DL (Bytes)",
        "HTTP UL (Bytes)",
        "Nb of sec with 125000B < Vol DL",
        "Nb of sec with 1250B < Vol UL < 6250B",
        "Nb of sec with 31250B < Vol DL < 125000B",
        "Nb of sec with 6250B < Vol DL < 31250B",
        "Nb of sec with Vol DL < 6250B",
        "Nb of sec with Vol UL < 1250B"
    ]

    imputer = SimpleImputer(strategy='mean')
    cleaned_df[columns_to_impute] = imputer.fit_transform(cleaned_df[columns_to_impute])
    return cleaned_df
imputed_df = impute_columns()

In [67]:
imputed_df.isnull().sum()

Bearer Id                                    990
Start                                          0
Start ms                                       0
End                                            0
End ms                                         0
Dur. (ms)                                      0
IMSI                                         569
MSISDN/Number                               1065
IMEI                                         571
Last Location Name                          1152
Avg RTT DL (ms)                                0
Avg RTT UL (ms)                                0
Avg Bearer TP DL (kbps)                        0
Avg Bearer TP UL (kbps)                        0
TCP DL Retrans. Vol (Bytes)                    0
TCP UL Retrans. Vol (Bytes)                    0
DL TP < 50 Kbps (%)                            0
50 Kbps < DL TP < 250 Kbps (%)                 0
250 Kbps < DL TP < 1 Mbps (%)                  0
DL TP > 1 Mbps (%)                             0
UL TP < 10 Kbps (%)                            0
10 Kbps < UL TP < 50 Kbps (%)                  0
50 Kbps < UL TP < 300 Kbps (%)                 0
UL TP > 300 Kbps (%)                           0
HTTP DL (Bytes)                                0
HTTP UL (Bytes)                                0
Activity Duration DL (ms)                      0
Activity Duration UL (ms)                      0
Dur. (ms).1                                    0
Handset Manufacturer                         571
Handset Type                                 571
Nb of sec with 125000B < Vol DL                0
Nb of sec with 1250B < Vol UL < 6250B          0
Nb of sec with 31250B < Vol DL < 125000B       0
Nb of sec with 6250B < Vol DL < 31250B         0
Nb of sec with Vol DL < 6250B                  0
Nb of sec with Vol UL < 1250B                  0
Social Media DL (Bytes)                        0
Social Media UL (Bytes)                        0
Google DL (Bytes)                              0
Google UL (Bytes)                              0
Email DL (Bytes)                               0
Email UL (Bytes)                               0
Youtube DL (Bytes)                             0
Youtube UL (Bytes)                             0
Netflix DL (Bytes)                             0
Netflix UL (Bytes)                             0
Gaming DL (Bytes)                              0
Gaming UL (Bytes)                              0
Other DL (Bytes)                               0
Other UL (Bytes)                               0
Total UL (Bytes)                               0
Total DL (Bytes)                               0
dtype: int64

In [68]:
imputed_df.shape

(150000, 53)

**Replace columns with mode value**

In [70]:
def replace_with_mode():
    columns_to_replace = [
        'Bearer Id',
        'IMSI',
        'MSISDN/Number',
        'IMEI',
        'Last Location Name',
        'Handset Manufacturer',
        'Handset Type'
    ]
    imputer = SimpleImputer(strategy='most_frequent')
    cleaned_df[columns_to_replace] = imputer.fit_transform(cleaned_df[columns_to_replace])
    return cleaned_df

cleaned_df = replace_with_mode()

In [71]:
cleaned_df.isnull().sum()

Bearer Id                                   0
Start                                       0
Start ms                                    0
End                                         0
End ms                                      0
Dur. (ms)                                   0
IMSI                                        0
MSISDN/Number                               0
IMEI                                        0
Last Location Name                          0
Avg RTT DL (ms)                             0
Avg RTT UL (ms)                             0
Avg Bearer TP DL (kbps)                     0
Avg Bearer TP UL (kbps)                     0
TCP DL Retrans. Vol (Bytes)                 0
TCP UL Retrans. Vol (Bytes)                 0
DL TP < 50 Kbps (%)                         0
50 Kbps < DL TP < 250 Kbps (%)              0
250 Kbps < DL TP < 1 Mbps (%)               0
DL TP > 1 Mbps (%)                          0
UL TP < 10 Kbps (%)                         0
10 Kbps < UL TP < 50 Kbps (%)               0
50 Kbps < UL TP < 300 Kbps (%)              0
UL TP > 300 Kbps (%)                        0
HTTP DL (Bytes)                             0
HTTP UL (Bytes)                             0
Activity Duration DL (ms)                   0
Activity Duration UL (ms)                   0
Dur. (ms).1                                 0
Handset Manufacturer                        0
Handset Type                                0
Nb of sec with 125000B < Vol DL             0
Nb of sec with 1250B < Vol UL < 6250B       0
Nb of sec with 31250B < Vol DL < 125000B    0
Nb of sec with 6250B < Vol DL < 31250B      0
Nb of sec with Vol DL < 6250B               0
Nb of sec with Vol UL < 1250B               0
Social Media DL (Bytes)                     0
Social Media UL (Bytes)                     0
Google DL (Bytes)                           0
Google UL (Bytes)                           0
Email DL (Bytes)                            0
Email UL (Bytes)                            0
Youtube DL (Bytes)                          0
Youtube UL (Bytes)                          0
Netflix DL (Bytes)                          0
Netflix UL (Bytes)                          0
Gaming DL (Bytes)                           0
Gaming UL (Bytes)                           0
Other DL (Bytes)                            0
Other UL (Bytes)                            0
Total UL (Bytes)                            0
Total DL (Bytes)                            0
dtype: int64

In [72]:
cleaned_df.shape

(150000, 53)

**Remove outliers**

In [76]:
def handle_outliers(cleaned_df, columns):
    df = cleaned_df.copy()
    for col in columns:
        # Calculate outlier bounds (replace with your chosen method)
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Replace outliers with NaN (or any other strategy)
        df[col] = np.where((df[col] < lower_bound) | (df[col] > upper_bound),
                           np.nan, df[col])
    return df

In [77]:
columns = [
    "Avg RTT DL (ms)",
    "Avg RTT UL (ms)",
    "TCP DL Retrans. Vol (Bytes)",
    "TCP UL Retrans. Vol (Bytes)",
    "DL TP < 50 Kbps (%)",
    "50 Kbps < DL TP < 250 Kbps (%)",
    "250 Kbps < DL TP < 1 Mbps (%)",
    "DL TP > 1 Mbps (%)",
    "UL TP < 10 Kbps (%)",
    "10 Kbps < UL TP < 50 Kbps (%)",
    "50 Kbps < UL TP < 300 Kbps (%)",
    "UL TP > 300 Kbps (%)",
    "HTTP DL (Bytes)",
    "HTTP UL (Bytes)",
    "Nb of sec with 125000B < Vol DL",
    "Nb of sec with 1250B < Vol UL < 6250B",
    "Nb of sec with 31250B < Vol DL < 125000B",
    "Nb of sec with 6250B < Vol DL < 31250B",
    "Nb of sec with Vol DL < 6250B",
    "Nb of sec with Vol UL < 1250B"
]


processed_df = handle_outliers(cleaned_df.copy(), columns)

In [78]:
processed_df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,13114500000000000000.0,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,208201000000000.0,33664962239.0,35521200000000.0,9.16457E+15,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,13114500000000000000.0,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,208202000000000.0,33681854413.0,35794000000000.0,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,13114500000000000000.0,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,208200000000000.0,33760627129.0,35281500000000.0,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,13114500000000000000.0,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,208201000000000.0,33750343200.0,35356600000000.0,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,13114500000000000000.0,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,208201000000000.0,33699795932.0,35407000000000.0,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [79]:
processed_df.shape

(150000, 53)

In [82]:
processed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150000 entries, 0 to 149999
Data columns (total 53 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 150000 non-null  object
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      150000 non-null  object
 7   MSISDN/Number                             150000 non-null  object
 8   IMEI                                      150000 non-null  object
 9   Last Location Name                        150000 non-null  object
 10  Avg RTT DL (ms)                           142282 non-null  float64
 11  Avg RTT UL (ms)                           141025 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               147475 non-null  float64
 15  TCP UL Retrans. Vol (Bytes)               148680 non-null  float64
 16  DL TP < 50 Kbps (%)                       131648 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            134780 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             120249 non-null  float64
 19  DL TP > 1 Mbps (%)                        127154 non-null  float64
 20  UL TP < 10 Kbps (%)                       127877 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             117210 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            144666 non-null  float64
 23  UL TP > 300 Kbps (%)                      146752 non-null  float64
 24  HTTP DL (Bytes)                           144585 non-null  float64
 25  HTTP UL (Bytes)                           143762 non-null  float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      150000 non-null  object
 30  Handset Type                              150000 non-null  object
 31  Nb of sec with 125000B < Vol DL           142240 non-null  float64
 32  Nb of sec with 1250B < Vol UL < 6250B     144230 non-null  float64
 33  Nb of sec with 31250B < Vol DL < 125000B  140827 non-null  float64
 34  Nb of sec with 6250B < Vol DL < 31250B    139201 non-null  float64
 35  Nb of sec with Vol DL < 6250B             126146 non-null  float64
 36  Nb of sec with Vol UL < 1250B             125455 non-null  float64
 37  Social Media DL (Bytes)                   150000 non-null  float64
 38  Social Media UL (Bytes)                   150000 non-null  float64
 39  Google DL (Bytes)                         150000 non-null  float64
 40  Google UL (Bytes)                         150000 non-null  float64
 41  Email DL (Bytes)                          150000 non-null  float64
 42  Email UL (Bytes)                          150000 non-null  float64
 43  Youtube DL (Bytes)                        150000 non-null  float64
 44  Youtube UL (Bytes)                        150000 non-null  float64
 45  Netflix DL (Bytes)                        150000 non-null  float64
 46  Netflix UL (Bytes)                        150000 non-null  float64
 47  Gaming DL (Bytes)                         150000 non-null  float64
 48  Gaming UL (Bytes)                         150000 non-null  float64
 49  Other DL (Bytes)                          150000 non-null  float64
 50  Other UL (Bytes)                          150000 non-null  float64
 51  Total UL (Bytes)                          150000 non-null  float64
 52  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(44), object(9)
memory usage: 61.8+ MB

In [84]:
processed_df.describe()

,Start ms,End ms,Dur. (ms),Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,150000.000000,150000.000000,1.500000e+05,142282.000000,141025.000000,150000.000000,150000.000000,1.474750e+05,1.486800e+05,131648.000000,...,1.500000e+05,1.500000e+05,1.500000e+05,1.500000e+05,1.500000e+05,1.500000e+05,1.500000e+05,1.500000e+05,1.500000e+05,1.500000e+05
mean,499.188200,498.800880,1.046086e+05,64.772444,10.280024,13300.045927,1770.428647,1.382499e+07,5.271031e+05,96.982310,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,288.611834,288.097653,8.103762e+04,38.850303,8.833056,23971.878541,4625.355500,9.686171e+06,3.417231e+05,5.601959,...,6.710591e+06,6.345445e+06,6.725240e+06,6.359511e+06,2.439683e+08,4.782716e+06,2.432058e+08,4.769020e+06,1.127639e+07,2.441429e+08
min,0.000000,0.000000,7.142000e+03,0.000000,0.000000,0.000000,0.000000,2.000000e+00,1.000000e+00,78.000000,...,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,250.000000,251.000000,5.744050e+04,34.000000,3.000000,43.000000,47.000000,1.235266e+06,6.096275e+04,97.000000,...,5.833482e+06,5.517962e+06,5.777095e+06,5.475977e+06,2.104706e+08,4.128424e+06,2.101824e+08,4.145904e+06,3.322201e+07,2.431068e+08
50%,499.000000,500.000000,8.639900e+04,51.000000,6.000000,63.000000,63.000000,2.080991e+07,7.596587e+05,100.000000,...,1.161601e+07,1.101348e+07,1.164222e+07,1.099631e+07,4.234082e+08,8.291215e+06,4.218057e+08,8.267086e+06,4.114331e+07,4.558411e+08
75%,749.000000,750.000000,1.324302e+05,109.795706,17.662883,19710.750000,1120.000000,2.080991e+07,7.596587e+05,100.000000,...,1.744855e+07,1.651559e+07,1.747050e+07,1.650729e+07,6.331747e+08,1.243163e+07,6.316950e+08,1.238420e+07,4.903424e+07,6.657055e+08
max,999.000000,999.000000,1.859336e+06,221.000000,39.000000,378160.000000,58613.000000,5.002102e+07,1.804466e+06,100.000000,...,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

In [87]:
processed_df.isnull().sum()

Bearer Id                                       0
Start                                           0
Start ms                                        0
End                                             0
End ms                                          0
Dur. (ms)                                       0
IMSI                                            0
MSISDN/Number                                   0
IMEI                                            0
Last Location Name                              0
Avg RTT DL (ms)                              7718
Avg RTT UL (ms)                              8975
Avg Bearer TP DL (kbps)                         0
Avg Bearer TP UL (kbps)                         0
TCP DL Retrans. Vol (Bytes)                  2525
TCP UL Retrans. Vol (Bytes)                  1320
DL TP < 50 Kbps (%)                         18352
50 Kbps < DL TP < 250 Kbps (%)              15220
250 Kbps < DL TP < 1 Mbps (%)               29751
DL TP > 1 Mbps (%)                          22846
UL TP < 10 Kbps (%)                         22123
10 Kbps < UL TP < 50 Kbps (%)               32790
50 Kbps < UL TP < 300 Kbps (%)               5334
UL TP > 300 Kbps (%)                         3248
HTTP DL (Bytes)                              5415
HTTP UL (Bytes)                              6238
Activity Duration DL (ms)                       0
Activity Duration UL (ms)                       0
Dur. (ms).1                                     0
Handset Manufacturer                            0
Handset Type                                    0
Nb of sec with 125000B < Vol DL              7760
Nb of sec with 1250B < Vol UL < 6250B        5770
Nb of sec with 31250B < Vol DL < 125000B     9173
Nb of sec with 6250B < Vol DL < 31250B      10799
Nb of sec with Vol DL < 6250B               23854
Nb of sec with Vol UL < 1250B               24545
Social Media DL (Bytes)                         0
Social Media UL (Bytes)                         0
Google DL (Bytes)                               0
Google UL (Bytes)                               0
Email DL (Bytes)                                0
Email UL (Bytes)                                0
Youtube DL (Bytes)                              0
Youtube UL (Bytes)                              0
Netflix DL (Bytes)                              0
Netflix UL (Bytes)                              0
Gaming DL (Bytes)                               0
Gaming UL (Bytes)                               0
Other DL (Bytes)                                0
Other UL (Bytes)                                0
Total UL (Bytes)                                0
Total DL (Bytes)                                0
dtype: int64

In [88]:
processed_df.to_csv('cleaned_data.csv', index=False)